/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_photoprocessing_img_ImgProcessing */

#ifndef _Included_com_example_photoprocessing_img_ImgProcessing
#define _Included_com_example_photoprocessing_img_ImgProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_photoprocessing_img_ImgProcessing
 * Method:    openCVBlur
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_photoprocessing_img_ImgProcessing_openCVBlur
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
